### ISSUE TITLE
Scheduled task cancelling

### ISSUE THREAD

**Issue by Haiethan1** [Haiethan1/ValorantApp#52]
Seems like the scheduled task starts to cancel after a discord disconnect and reconnect?.. 
and then the api takes forever to load too

**Comment by Haiethan1** [comment]
2024-01-23 21:20:40.057 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:20:46.958 -05:00 [WRN] SendScheduledMessage: Could not find user match stats
2024-01-23 21:21:16.960 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:21:22.848 -05:00 [WRN] SendScheduledMessage: Could not find user match stats
2024-01-23 21:21:52.848 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:22:02.179 -05:00 [WRN] SendScheduledMessage: Could not find user match stats
2024-01-23 21:22:32.174 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:23:27.288 -05:00 [INF] Discord LogAsync 21:23:27 Gateway     Discord.WebSocket.GatewayReconnectException: Server missed last heartbeat
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
2024-01-23 21:23:27.289 -05:00 [INF] Discord LogAsync 21:23:27 Gateway     Disconnecting
2024-01-23 21:23:27.293 -05:00 [INF] Discord LogAsync 21:23:27 Gateway     Disconnected
2024-01-23 21:23:28.294 -05:00 [INF] Discord LogAsync 21:23:28 Gateway     Connecting
2024-01-23 21:23:58.303 -05:00 [INF] Discord LogAsync 21:23:58 Gateway     System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
2024-01-23 21:23:58.303 -05:00 [INF] Discord LogAsync 21:23:58 Gateway     Disconnecting
2024-01-23 21:23:58.308 -05:00 [INF] Discord LogAsync 21:23:58 Gateway     Disconnected
2024-01-23 21:24:00.101 -05:00 [INF] Discord LogAsync 21:24:00 Gateway     Connecting
2024-01-23 21:24:07.272 -05:00 [INF] Discord LogAsync 21:24:07 Gateway     Failed to resume previous session
2024-01-23 21:24:07.530 -05:00 [INF] Discord LogAsync 21:24:07 Gateway     You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
2024-01-23 21:24:07.531 -05:00 [INF] Discord LogAsync 21:24:07 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
2024-01-23 21:24:07.531 -05:00 [INF] Discord LogAsync 21:24:07 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
2024-01-23 21:24:07.531 -05:00 [INF] Discord LogAsync 21:24:07 Gateway     Connected
2024-01-23 21:24:08.031 -05:00 [INF] ValorantDataBot is connected!
2024-01-23 21:24:08.032 -05:00 [INF] Discord LogAsync 21:24:08 Gateway     Ready
2024-01-23 21:24:12.494 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:24:42.493 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:26:22.612 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:26:52.616 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:28:31.467 -05:00 [INF] Discord LogAsync 21:28:31 Gateway     System.Exception: WebSocket connection was closed
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
2024-01-23 21:28:31.468 -05:00 [INF] Discord LogAsync 21:28:31 Gateway     Disconnecting
2024-01-23 21:28:31.468 -05:00 [INF] Discord LogAsync 21:28:31 Gateway     Disconnected
2024-01-23 21:28:32.469 -05:00 [INF] Discord LogAsync 21:28:32 Gateway     Connecting
2024-01-23 21:28:32.730 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:28:32.837 -05:00 [INF] Discord LogAsync 21:28:32 Gateway     Resumed previous session
2024-01-23 21:28:32.837 -05:00 [INF] Discord LogAsync 21:28:32 Gateway     You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
2024-01-23 21:28:32.837 -05:00 [INF] Discord LogAsync 21:28:32 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
2024-01-23 21:28:32.837 -05:00 [INF] Discord LogAsync 21:28:32 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
2024-01-23 21:28:32.837 -05:00 [INF] Discord LogAsync 21:28:32 Gateway     Connected
2024-01-23 21:29:02.731 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:30:17.613 -05:00 [INF] Discord LogAsync 21:30:17 Gateway     Discord.WebSocket.GatewayReconnectException: Server missed last heartbeat
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
2024-01-23 21:30:17.614 -05:00 [INF] Discord LogAsync 21:30:17 Gateway     Disconnecting
2024-01-23 21:30:17.617 -05:00 [INF] Discord LogAsync 21:30:17 Gateway     Disconnected
2024-01-23 21:30:18.614 -05:00 [INF] Discord LogAsync 21:30:18 Gateway     Connecting
2024-01-23 21:30:43.126 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:31:13.127 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:31:23.488 -05:00 [INF] Discord LogAsync 21:31:23 Gateway     System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Discord.Net.WebSockets.DefaultWebSocketClient.ConnectInternalAsync(String host)
   at Discord.Net.WebSockets.DefaultWebSocketClient.ConnectAsync(String host)
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
2024-01-23 21:31:23.489 -05:00 [INF] Discord LogAsync 21:31:23 Gateway     Disconnecting
2024-01-23 21:31:23.489 -05:00 [INF] Discord LogAsync 21:31:23 Gateway     Disconnected
2024-01-23 21:31:25.476 -05:00 [INF] Discord LogAsync 21:31:25 Gateway     Connecting
2024-01-23 21:31:43.848 -05:00 [INF] Discord LogAsync 21:31:43 Gateway     Resumed previous session
2024-01-23 21:31:43.848 -05:00 [INF] Discord LogAsync 21:31:43 Gateway     You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
2024-01-23 21:31:43.849 -05:00 [INF] Discord LogAsync 21:31:43 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
2024-01-23 21:31:43.849 -05:00 [INF] Discord LogAsync 21:31:43 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
2024-01-23 21:31:43.849 -05:00 [INF] Discord LogAsync 21:31:43 Gateway     Connected
2024-01-23 21:32:53.521 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (The SSL connection could not be established, see inner exception.))
2024-01-23 21:33:23.521 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:35:03.612 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (The SSL connection could not be established, see inner exception.))
2024-01-23 21:35:33.615 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:37:13.730 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:37:43.725 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:39:23.837 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:39:53.838 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:41:34.119 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:42:04.122 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:43:44.254 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:44:14.249 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:45:54.385 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:46:24.386 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:48:04.614 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:48:34.615 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:50:14.726 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:50:44.721 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:52:24.837 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:52:54.840 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:54:35.188 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:55:05.190 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:56:45.313 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 21:57:15.311 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 21:58:55.493 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (The SSL connection could not be established, see inner exception.))
2024-01-23 21:59:25.496 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 22:01:05.722 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 22:01:35.721 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 22:03:15.844 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 22:03:45.844 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 22:05:25.957 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))
2024-01-23 22:05:55.960 -05:00 [INF] Starting Send of scheduled messages.
2024-01-23 22:07:36.126 -05:00 [ERR] Error: SendScheduledMessage - One or more errors occurred. (One or more errors occurred. (A task was canceled.))

**Comment by Haiethan1** [comment]
![image](https://github.com/Haiethan1/ValorantApp/assets/54637324/4755c520-8085-4835-a449-029be17552e5)

**Comment by Haiethan1** [comment]
was fixed by using ethernet.
